# Generated by Django 3.1.4 on 2021-01-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='Some Image', upload_to='images/'),
        ),
    ]
